export const projects = [
  {
    title: 'Front-End Project',
    subtitle: 'Web Portfolio - In Progress',
    timeline: 'February 2022 - Present',
    stakeholders: 'JavaScript Mastery',
    description1: "• Developed SPA showcasing personal SD projects, SE expertise & media projects using React and Next.js",
    description2: "• Utilized component based and global based styling in conjunction with CSS Flexbox layout design to ensure proper scaling across mobile and desktop screens",
    tags: ['Next.js', 'React.js'],
    visit: 'https://www.nuriev.ca',
    source: 'https://github.com/maximusyellow/WebPortfolio',
    id: 0,
  },
  {
    title: 'Capstone Project',
    subtitle: 'Routing Protocols Collector',
    timeline: 'September 2021 - April 2022',
    stakeholders: 'University of Ottawa & Ciena Corporation',
    description1: "• Implemented support for OSPFv3 and BGP routing protocols for a Java based routing protocols collector application to analyze network logs for Ciena clients using MVC approach",
    description2: "• Upgraded parsing capabilities on a Python log parser to support OSPFv3 network logs",
    tags: ['Python','Java'],
    id: 1,
  },
  {
    title: 'Desktop App Project',
    subtitle: 'Image Editing Software',
    timeline: 'September 2016 - December 2016',
    stakeholders: '',
    description1: "• Developed a Paint application entirely with Python and Tkinter GUI",
    description2: "• Implemented features for undo/redo as well as saving/loading existing artwork",
    tags: ['Python','Tkinter'],
    source: 'https://github.com/maximusyellow/paint',
    id: 2,
  },
];

export const TimeLineData = [
  { year: 2015, text: 'Started learning Python and Java', },
  { year: 2016, text: 'Started Software Engineering studies at uOttawa', },
  { year: 2018, text: 'Worked as a Front-end Developer', },
  { year: 2019, text: 'Worked as a Firmware Engineer', },
  { year: 2020, text: 'Worked on my SEG Capstone Project', },
  { year: 2021, text: 'Worked as a Software Developer for embedded devices', },
  { year: 2022, text: 'Creating sites as a freelance web developer', },
];